In [ ]:
!pip install sentence-transformers datasets chromadb unstructured transformers Chroma tiktoken langchain==0.1.1  huggingface_hub

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.10/dist-packages (2.3.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (2.17.0)
Requirement already satisfied: chromadb in /usr/local/lib/python3.10/dist-packages (0.4.22)
Requirement already satisfied: unstructured in /usr/local/lib/python3.10/dist-packages (0.12.4)
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.35.2)
Requirement already satisfied: Chroma in /usr/local/lib/python3.10/dist-packages (0.2.0)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.10/dist-packages (0.6.0)
Requirement already satisfied: langchain==0.1.1 in /usr/local/lib/python3.10/dist-packages (0.1.1)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.10/dist-packages (0.20.3)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.10/dist-packages (from langchain==0.1.1) (6.0.1)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.10/dist-packages (from langchain==0.1.1) (2.0.25)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.10/dist-packages (from langchain==0.1.1) (3.9.3)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from langchain==0.1.1) (4.0.3)
Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /usr/local/lib/python3.10/dist-packages (from langchain==0.1.1) (0.6.4)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.10/dist-packages (from langchain==0.1.1) (1.33)
Requirement already satisfied: langchain-community<0.1,>=0.0.13 in /usr/local/lib/python3.10/dist-packages (from langchain==0.1.1) (0.0.19)
Requirement already satisfied: langchain-core<0.2,>=0.1.9 in /usr/local/lib/python3.10/dist-packages (from langchain==0.1.1) (0.1.22)
Requirement already satisfied: langsmith<0.1.0,>=0.0.77 in /usr/local/lib/python3.10/dist-packages (from langchain==0.1.1) (0.0.87)
Requirement already satisfied: numpy<2,>=1 in /usr/local/lib/python3.10/dist-packages (from langchain==0.1.1) (1.23.5)
Requirement already satisfied: pydantic<3,>=1 in /usr/local/lib/python3.10/dist-packages (from langchain==0.1.1) (2.6.1)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.10/dist-packages (from langchain==0.1.1) (2.31.0)
Requirement already satisfied: tenacity<9.0.0,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from langchain==0.1.1) (8.2.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.66.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (2.1.0+cu121)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.11.4)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (3.8.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.1.99)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (9.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.13.1)
Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (15.0.0)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets) (0.6)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (1.5.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec[http]<=2023.10.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2023.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (23.2)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.0.3)
Requirement already satisfied: chroma-hnswlib==0.7.3 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.7.3)
Requirement already satisfied: fastapi>=0.95.2 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.109.2)
Requirement already satisfied: uvicorn[standard]>=0.18.3 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.27.1)
Requirement already satisfied: posthog>=2.4.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (3.4.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (4.9.0)
Requirement already satisfied: pulsar-client>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (3.4.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.17.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.22.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.22.0)
Requirement already satisfied: opentelemetry-instrumentation-fastapi>=0.41b0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.43b0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.22.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.15.1)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.48.9)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.10/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.10/dist-packages (from chromadb) (6.1.1)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.60.1)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from chromadb) (4.1.2)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.9.0)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (29.0.0)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from chromadb) (4.1.0)
Requirement already satisfied: chardet in /usr/local/lib/python3.10/dist-packages (from unstructured) (5.2.0)
Requirement already satisfied: filetype in /usr/local/lib/python3.10/dist-packages (from unstructured) (1.2.0)
Requirement already satisfied: python-magic in /usr/local/lib/python3.10/dist-packages (from unstructured) (0.4.27)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from unstructured) (4.9.4)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from unstructured) (0.9.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from unstructured) (4.12.3)
Requirement already satisfied: emoji in /usr/local/lib/python3.10/dist-packages (from unstructured) (2.10.1)
Requirement already satisfied: python-iso639 in /usr/local/lib/python3.10/dist-packages (from unstructured) (2024.2.7)
Requirement already satisfied: langdetect in /usr/local/lib/python3.10/dist-packages (from unstructured) (1.0.9)
Requirement already satisfied: rapidfuzz in /usr/local/lib/python3.10/dist-packages (from unstructured) (3.6.1)
Requirement already satisfied: backoff in /usr/local/lib/python3.10/dist-packages (from unstructured) (2.2.1)
Requirement already satisfied: unstructured-client>=0.15.1 in /usr/local/lib/python3.10/dist-packages (from unstructured) (0.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from unstructured) (1.14.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2023.12.25)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.2)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.1) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.1) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.1) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.1) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.1) (1.9.4)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.10/dist-packages (from build>=1.0.3->chromadb) (1.0.0)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from build>=1.0.3->chromadb) (2.0.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.10/dist-packages (from dataclasses-json<0.7,>=0.5.7->langchain==0.1.1) (3.20.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from dataclasses-json<0.7,>=0.5.7->langchain==0.1.1) (0.9.0)
Requirement already satisfied: starlette<0.37.0,>=0.36.3 in /usr/local/lib/python3.10/dist-packages (from fastapi>=0.95.2->chromadb) (0.36.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.10/dist-packages (from jsonpatch<2.0,>=1.33->langchain==0.1.1) (2.4)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2024.2.2)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.16.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.8.2)
Requirement already satisfied: google-auth>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.17.3)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.7.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.3.1)
Requirement already satisfied: oauthlib>=3.2.2 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (3.2.2)
Requirement already satisfied: urllib3>=1.24.2 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.7)
Requirement already satisfied: anyio<5,>=3 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.2,>=0.1.9->langchain==0.1.1) (3.7.1)
Requirement already satisfied: coloredlogs in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (15.0.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (23.5.26)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (3.20.3)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.12)
Requirement already satisfied: deprecated>=1.2.6 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (1.2.14)
Requirement already satisfied: importlib-metadata<7.0,>=6.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (6.11.0)
Requirement already satisfied: googleapis-common-protos~=1.52 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.62.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.22.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.22.0)
Requirement already satisfied: opentelemetry-proto==1.22.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.22.0)
Requirement already satisfied: opentelemetry-instrumentation-asgi==0.43b0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (0.43b0)
Requirement already satisfied: opentelemetry-instrumentation==0.43b0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (0.43b0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (0.43b0)
Requirement already satisfied: opentelemetry-util-http==0.43b0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (0.43b0)
Requirement already satisfied: setuptools>=16.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-instrumentation==0.43b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (67.7.2)
Requirement already satisfied: asgiref~=3.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-instrumentation-asgi==0.43b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (3.7.2)
Requirement already satisfied: monotonic>=1.5 in /usr/local/lib/python3.10/dist-packages (from posthog>=2.4.0->chromadb) (1.6)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1->langchain==0.1.1) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.2 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1->langchain==0.1.1) (2.16.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain==0.1.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain==0.1.1) (3.6)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<3,>=1.4->langchain==0.1.1) (3.0.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.3)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (2.1.0)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer>=0.9.0->chromadb) (8.1.7)
Requirement already satisfied: dataclasses-json-speakeasy>=0.5.11 in /usr/local/lib/python3.10/dist-packages (from unstructured-client>=0.15.1->unstructured) (0.5.11)
Requirement already satisfied: jsonpath-python>=1.0.6 in /usr/local/lib/python3.10/dist-packages (from unstructured-client>=0.15.1->unstructured) (1.0.6)
Requirement already satisfied: mypy-extensions>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from unstructured-client>=0.15.1->unstructured) (1.0.0)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.10/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.14.0)
Requirement already satisfied: httptools>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.6.1)
Requirement already satisfied: python-dotenv>=0.13 in /usr/local/lib/python3.10/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.0.1)
Requirement already satisfied: uvloop!=0.15.0,!=0.15.1,>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.19.0)
Requirement already satisfied: watchfiles>=0.13 in /usr/local/lib/python3.10/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.21.0)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.10/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (12.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->unstructured) (2.5)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers) (1.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2023.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (3.2.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3->langchain-core<0.2,>=0.1.9->langchain==0.1.1) (1.3.0)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3->langchain-core<0.2,>=0.1.9->langchain==0.1.1) (1.2.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (5.3.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (4.9)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata<7.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.17.0)
Requirement already satisfied: humanfriendly>=9.1 in /usr/local/lib/python3.10/dist-packages (from coloredlogs->onnxruntime>=1.14.1->chromadb) (10.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.5.1)

In [ ]:
from sentence_transformers import SentenceTransformer
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma

from langchain.document_loaders import TextLoader
from langchain.schema.document import Document
from datasets import load_dataset
from sentence_transformers import SentenceTransformer
import chromadb

In [ ]:
MODEL_MINILM = "sentence-transformers/all-MiniLM-L6-v2"
MODEL_MINILM_L12 = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
MODEL_distiluse= "sentence-transformers/distiluse-base-multilingual-cased-v2"
SAMPLE = 500
dim = 512

# model_id = "aubmindlab/bert-large-arabertv2"
# dim = 1024
# dim = 384
device = "cpu"

In [ ]:

ar_dataset = open("/content/drive/MyDrive/NLP/NLU/NLU/data/semantic_search/ar.txt").readlines()
en_dataset = open("/content/drive/MyDrive/NLP/NLU/NLU/data/semantic_search/en.txt").readlines()

In [ ]:
## Search
import pandas as pd
# test_questions = {
#     "question":[
#         "وا بتعليم أطفالهم القراءة منذ الصغر  يجب على الآباء ",
#         "فالقراءة مفيدة جداً في تنمية شخصية .",
#         "ان القراءة تساعد علي تنميه المهارات و تشغل الشخص عن المعاصى ",
#         "وهل يمكنني استخدام الزبيب كبديل عن الفياجرا لحل مشكلة ضعف الانتصاب؟	بداية أود"
#     ],
#     "answer":[
#         "والأمهات أن يقوموا بتعليم أطفالهم القراءة منذ الصغر  ",
#         "فالقراءة مفيدة جداً في تنمية شخصية الفرد واتساع مداركه.",
#         "حيث أن استغلال وقت الفراغ في قراءة الكتب النافعة ينمي قدرات ومهارات الفرد، ويشغله عن المعاصي والشهوات.",
#         "هل الزبيب مفيد للجماع؟ وهل يمكنني استخدام الزبيب كبديل عن الفياجرا لحل مشكلة ضعف الانتصاب؟	بداية أود التوضيح أنه لا يوجد ما يؤكد فاعلية الزبيب في علاج الاضطرابات الجنسية أو في تحسين الأداء الجنسي خلال الجماع  لذلك لا يمكن اعتبار الزبيب كبديل عن دواء الفياجرا لعلاج مشكلة ضعف الانتصاب وأنصحك في جميع الأحوال في حال وجود مشكلة جنسية بمراجعة الطبيب للكشف عن سببها لأن بعض مشاكل الضعف الجنسي قد تكون ناجمة عن مشاكل صحية أخرى ويمكن علاجها بكفاءة يجدر الذكر أن الزبيب يحتوي على عدد من الفيتامينات والمعادن التي قد تساهم في تحسين الصحة العامة للجسم وهو ما قد ينعكس على الصحة الجنسية أيضًا  ومن العناصر الغذائية في الزبيب والتي قد تلعب دورًا إيجابيًا في تعزيز الصحة الجنسية ما يلي: الحديد: يساعد الحديد على نقل الأكسجين إلى جميع أنحاء الجسم بما في ذلك الأعضاء التناسلية فيتامينات A وC وE: تلعب هذه الفيتامينات دورًا مهمًا في صحة الجهاز التناسلي بشكل عام الألياف: تساعد الألياف على تحسين عملية الهضم وبالتالي زيادة امتصاص العناصر الغذائية المهمة لسلامة الجهاز التناسلي يمكن تناول الزبيب كجزء من نظام غذائي صحي ومتوازن بالإضافة إلى ممارسة الرياضة بانتظام للاستفادة من فوائده الصحية على الجسم بشكل عام "
#     ],
#     "type-of-question":[
#         "تعليم الابنناء",
#         "القراءه",
#         "اهميه القراءه",
#         "الزبيب في علاج"
#     ]

# }
en_test_questions = {
    "question":[
        "reasons for reading it may be slightly",
        "Reading was a skill we developed as we grew up ",
        "We probably guess words before we read them,",
        "we meet with the best football player in the world right now "
    ],
    "answer":[
        " so our reasons for reading it may be slightly more complex than simply for pleasure",
        "Reading was a skill we developed as we grew up and as we became acquainted with different types of text",
        "We almost certainly predict words before we read them, especially as there are some conventions to a postcard.",
        " we meet with the best football player in the world right now"
    ],
    "type-of-question":[
        "reasons for reading",
        "Reading is a skill",
        "guess words",
        "best football player"
    ]

}
df = pd.DataFrame(en_test_questions)
df.head()

,question,answer,type-of-question
0,reasons for reading it may be slightly,so our reasons for reading it may be slightly...,reasons for reading
1,Reading was a skill we developed as we grew up,Reading was a skill we developed as we grew up...,Reading is a skill
2,"We probably guess words before we read them,",We almost certainly predict words before we re...,guess words
3,we meet with the best football player in the w...,we meet with the best football player in the ...,best football player

In [ ]:
en_dataset= "".join(en_dataset)

In [ ]:
distiluse = HuggingFaceEmbeddings(model_name="sentence-transformers/distiluse-base-multilingual-cased-v2")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
def process_and_embed_docs(embeddings, data, model_name):
  loaded_docs = [Document(page_content=data, metadata={'source': 'local'})]
  splitter = RecursiveCharacterTextSplitter(
      separators = [". ", ".", "\n\n", "\n", " ", ""],
      chunk_size=200, chunk_overlap=0
  )
  split_docs = splitter.split_documents(loaded_docs)
  database = Chroma.from_documents(
      documents=split_docs, embedding=embeddings,
      collection_metadata={"hnsw:space": "cosine"}
  )

  return database
def semantic_search(embeddings, model_name, input_text: str,  query: str):
        db = process_and_embed_docs(embeddings, input_text, model_name)

        retrieved_docs = db.similarity_search_with_relevance_scores(query)
        print(retrieved_docs)
        results = []
        matches = []
        for d in retrieved_docs:
            match = d[0].page_content
            sim = d[1]
            if sim >= 0.6:
                start = input_text.index(match)
                end = start + len(match)
                if match not in results:
                    results.append(match)
                    matches.append({"result": match, "start": start, "end": end, "similarity": sim})

        return {"query": query, "matches": matches}

In [ ]:
results_distiluse = []
for question in df['question']:
  print(question)
  results_distiluse.append(semantic_search(distiluse, "./distiluse",en_dataset,  question) )

reasons for reading it may be slightly
[(Document(page_content='.\n\nWhy do we read?\nThere are a number of reasons why we read, and this will often influence what we read and how we read it', metadata={'source': 'local'}), 0.6147994995117188), (Document(page_content='. We could also be reading the lyrics to a song, so our reasons for reading it may be slightly more complex than simply for pleasure', metadata={'source': 'local'}), 0.49676305055618286), (Document(page_content='.\nRationale: Identifying the type of text and where you might read it supplies the reader with some context', metadata={'source': 'local'}), 0.4438976049423218), (Document(page_content='What is reading?\nAt the most basic level reading is the recognition of words', metadata={'source': 'local'}), 0.41316938400268555)]
Reading was a skill we developed as we grew up
[(Document(page_content='. Reading was a skill we developed as we grew up and as we became acquainted with different types of text. Once we start seeing these texts in a foreign language we are unable to decode the message', metadata={'source': 'local'}), 0.6114535331726074), (Document(page_content='. Reading was a skill we developed as we grew up and as we became acquainted with different types of text. Once we start seeing these texts in a foreign language we are unable to decode the message', metadata={'source': 'local'}), 0.6114535331726074), (Document(page_content='What is reading?\nAt the most basic level reading is the recognition of words', metadata={'source': 'local'}), 0.48180919885635376), (Document(page_content='What is reading?\nAt the most basic level reading is the recognition of words', metadata={'source': 'local'}), 0.48180919885635376)]
We probably guess words before we read them,
[(Document(page_content='. We almost certainly predict words before we read them, especially as there are some conventions to a postcard', metadata={'source': 'local'}), 0.6868205070495605), (Document(page_content='. We almost certainly predict words before we read them, especially as there are some conventions to a postcard', metadata={'source': 'local'}), 0.6868205070495605), (Document(page_content='. We almost certainly predict words before we read them, especially as there are some conventions to a postcard', metadata={'source': 'local'}), 0.6868205070495605), (Document(page_content='. We start to read every word in a way that we wouldn’t if the text was in our L1', metadata={'source': 'local'}), 0.4907870292663574)]
we meet with the best football player in the world right now
[(Document(page_content='. We start to read every word in a way that we wouldn’t if the text was in our L1', metadata={'source': 'local'}), 0.14140045642852783), (Document(page_content='. We start to read every word in a way that we wouldn’t if the text was in our L1', metadata={'source': 'local'}), 0.14140045642852783), (Document(page_content='. We start to read every word in a way that we wouldn’t if the text was in our L1', metadata={'source': 'local'}), 0.14140045642852783), (Document(page_content='. We start to read every word in a way that we wouldn’t if the text was in our L1', metadata={'source': 'local'}), 0.14140045642852783)]

In [ ]:
df_results  = pd.read_csv("/content/drive/MyDrive/NLP/NLU/NLU/data/semantic_search/en-results.csv")

In [ ]:
df_results.head()

,questions,answers,MINILM_L12
0,reasons for reading it may be slightly,so our reasons for reading it may be slightly...,{'query': 'reasons for reading it may be sligh...
1,Reading was a skill we developed as we grew up,Reading was a skill we developed as we grew up...,{'query': 'Reading was a skill we developed as...
2,"We probably guess words before we read them,",We almost certainly predict words before we re...,{'query': 'We probably guess words before we r...
3,we meet with the best football player in the w...,we meet with the best football player in the ...,{'query': 'we meet with the best football play...

In [ ]:
df_results = df_results.drop("distiluse",axis=1)

In [ ]:
df_results['distiluse'] = results_distiluse

In [ ]:

df_results.to_csv("/content/drive/MyDrive/NLP/NLU/NLU/data/semantic_search/en-results.csv", index=False)