In [ ]:
!pip install camel_tools

Requirement already satisfied: camel_tools in /usr/local/lib/python3.10/dist-packages (1.5.2)
Requirement already satisfied: future in /usr/local/lib/python3.10/dist-packages (from camel_tools) (0.18.3)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from camel_tools) (1.16.0)
Requirement already satisfied: docopt in /usr/local/lib/python3.10/dist-packages (from camel_tools) (0.6.2)
Requirement already satisfied: cachetools in /usr/local/lib/python3.10/dist-packages (from camel_tools) (5.3.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from camel_tools) (1.22.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from camel_tools) (1.10.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from camel_tools) (1.5.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from camel_tools) (1.2.2)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from camel_tools) (0.3.6)
Requirement already satisfied: torch>=1.3 in /usr/local/lib/python3.10/dist-packages (from camel_tools) (2.0.1+cu118)
Requirement already satisfied: transformers>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from camel_tools) (4.31.0)
Requirement already satisfied: editdistance in /usr/local/lib/python3.10/dist-packages (from camel_tools) (0.6.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from camel_tools) (2.27.1)
Requirement already satisfied: emoji in /usr/local/lib/python3.10/dist-packages (from camel_tools) (2.6.0)
Requirement already satisfied: pyrsistent in /usr/local/lib/python3.10/dist-packages (from camel_tools) (0.19.3)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from camel_tools) (0.8.10)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from camel_tools) (4.65.0)
Requirement already satisfied: muddler in /usr/local/lib/python3.10/dist-packages (from camel_tools) (0.1.3)
Requirement already satisfied: camel-kenlm>=2023.3.17.2 in /usr/local/lib/python3.10/dist-packages (from camel_tools) (2023.3.17.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.3->camel_tools) (3.12.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.3->camel_tools) (4.7.1)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.3->camel_tools) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.3->camel_tools) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.3->camel_tools) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.3->camel_tools) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.3->camel_tools) (3.25.2)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.3->camel_tools) (16.0.6)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.2->camel_tools) (0.16.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.2->camel_tools) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.2->camel_tools) (6.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.2->camel_tools) (2022.10.31)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.2->camel_tools) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.2->camel_tools) (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->camel_tools) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->camel_tools) (2022.7.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->camel_tools) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->camel_tools) (2023.5.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->camel_tools) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->camel_tools) (3.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->camel_tools) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->camel_tools) (3.1.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers>=3.0.2->camel_tools) (2023.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.3->camel_tools) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.3->camel_tools) (1.3.0)

In [ ]:
from camel_tools.ner import NERecognizer
from camel_tools.tokenizers.word import simple_word_tokenize

import re

In [ ]:

def has_no_arabic_chars(word):

    pattern =  r'[«#>\]_*,;%@+/:^)~»<?$؛({\'!}=.\[\\"`،|\-&]'
    return re.sub(pattern, '', word)


def clean_data(word, label):
  if has_no_arabic_chars(word) =='': return [], []
  else : return has_no_arabic_chars(word), label

def split_text_file(filename):
    with open(filename ,'r', encoding='utf-8') as file:
        lines = file.readlines()
    data = [];
    for line in lines:
        line = line.strip()
        if line:
            parts = line.split('\t')
            text = parts[0]
            _sentence = text.split(" ")
            _labels = parts[1:][0].split(" ")
            sentence= []; labels =[]
            for i, word in enumerate(_sentence):
              tmp_sen, tmp_leb = clean_data(word, _labels[i])
              if tmp_sen != []: sentence.append(tmp_sen); labels.append(tmp_leb)
            data.append((sentence, labels))

    return data


data= split_text_file("/content/drive/MyDrive/projects/NER/b.txt")

In [ ]:

ner = NERecognizer('CAMeL-Lab/bert-base-arabic-camelbert-mix-ner')

Some weights of the model checkpoint at CAMeL-Lab/bert-base-arabic-camelbert-mix-ner were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [ ]:

label_convert = {
    "B-LOC":"loc", "I-LOC":"loc","B-ORG":"org","I-ORG":"org",
    "I-PERS":"per", "B-PERS":"per", "O":"O", "B-COM": "O",
    "I-COM": "O","B-MISC" :"misc", "I-MISC":"misc",
}


def predict_data(sentence, nlp):
  annotations = nlp.predict_sentence(sentence)
  entities = []
  tags = []
  for i, _sentence in enumerate(sentence):
    entities.append(_sentence) ; tags.append(label_convert[annotations[i]])
  return entities, tags

predicted_data = []

data_values = []
count = 0
print(len(data))
for X, y in data:
  if count%50 == 0: print(count); print(X)
  data_values.append((X, y))
  predicted_data.append(predict_data(X, ner))
  count +=1

922
0
['الصالحية', 'المفرق', 'غيث', 'الطراونة', 'أمر', 'جلالة', 'الملك', 'عبدالله', 'الثاني', 'أمس', 'بتنفيذ', 'حزمة', 'من', 'المشاريع', 'التعليمية', 'والصحية', 'والتنموية', 'وأخرى', 'مرتبطة', 'بالأندية', 'الشبابية', 'و', '27', 'وحدة', 'سكنية', 'في', 'قضاء', 'الصالحية', 'ونايفة', 'في', 'البادية', 'الشرقية', 'خلال', 'ستة', 'اشهر', 'بتمويل', 'من', 'الديوان', 'الملكي', 'الهاشمي']
50
['بلدة', 'إن', 'وودورد', 'رسم', 'في', 'كتابه', 'حالة', 'النكران', 'صورة', 'للصراعات', 'الشخصية', 'الحادة', 'داخل', 'الإدارة', 'الأميركية', 'مشيرا', 'إلى', 'أن', 'آندرو', 'كارل', 'رئيس', 'موظفي', 'إدارة', 'البيت', 'الأبيض', 'السابق', 'حاول', 'مرتين', 'إجبار', 'دونالد', 'رمسفيلد', 'وزير', 'الدفاع', 'الأميركي', 'على', 'الاستقالة', 'على', 'خلفية', 'إدارته', 'للحرب', 'على', 'العراق']
100
['ثانية', 'البابا', 'قد', 'اقتبس', 'في', 'محاضرة', 'ألقاها', 'في', 'راتيسبون', 'بألمانيا', 'في', '12', 'سبتمبر', 'أيلول', 'عن', 'إمبراطور', 'بيزنطي', 'في', 'القرن', 'ال', 'ـ', '14', 'حديثا', 'عن', 'العلاقة', 'بين', 'الإسلام', 'والعنف']
150
['وقال', 'منه', 'رويترز', 'تأكيد', 'تصريحاته', 'للتلفزيون', 'الهولندي', 'امس', 'الاول', 'بأنه', 'ينوي', 'البقاء', 'في', 'منصبه', 'حتي', 'نفس', 'الوقت', 'من', 'العام', 'المقبل', 'قال', 'دويسنبرج', 'نعم']
200
['اقليم', 'الأميركي', 'دونالد', 'وبالمر', 'علي', 'الزوجي', 'الأسباني', 'فيسنت', 'وبورتاس', '6', '2', 'و6', '4']
250
['الشرق', 'حزب', 'العمال', 'الكردستاني', 'الذي', 'يعتبره', 'الاتحاد', 'الاوروبي', 'والولايات', 'المتحدة', 'وتركيا', 'منظمة', 'ارهابية', 'اعلن', 'عدة', 'هدنات', 'في', 'السابق', 'لكن', 'القادة', 'المدنيين', 'والعسكريين', 'الاتراك', 'لم', 'يعترفوا', 'بها', 'ابداً']
300
['العالمية', 'الدورية', 'العسكرية', 'في', 'كمين', 'نسب', 'لجماعة', 'مسلحة', 'تنتمي', 'للجماعة', 'السلفية', 'للتبشير', 'والجهاد', 'على', 'الطريق', 'الوطني', 'رقم12', 'الرابط', 'بين', 'ادكار', 'والقصور', 'في', 'بجاية']
350
['ولمافشلت', 'بإمكانها', 'أن', 'تستخدم', 'المكتب', 'الذي', 'تعمل', 'فيه']
400
['آخر', 'الفريق', 'العائد', 'الى', 'الأرض', 'معه', 'مجموعة', 'من', 'الديدان', 'والحشرات', 'والنباتات', 'التي', 'وُلدت', 'وأنبتت', 'على', 'متن', 'المحطة', 'الفضائية', 'الدولية']
450
['لا', 'دانت', 'المحكمة', 'أبو', 'فارس', 'وأبو', 'السكر', 'وبالتالي', 'حكمت', 'على', 'الأول', 'بسنتين', 'والثاني', 'سنة', 'ونصف', 'ثم', 'عادت', 'محكمة', 'التمييز', 'لتخفض', 'العقوبة', 'على', 'الرجلين', 'الى', 'سنة', 'وشهر', 'لكل', 'منهما']
500
['أن', 'متراً']
550
['الأسود', 'المسافرين', 'بمطار', 'غاتويك', 'البريطاني', 'بسبب', 'الإجراءات', 'الأمنية', 'رويترز', 'أرشيف']
600
['البسهاوزن', 'إلى', 'أن', 'عبلة', 'في', 'المعرض', 'الذي', 'يستمر', 'حتى', '15', 'أكتوبر', 'تشرين', 'الأول', 'يبدو', 'مرتبطا', 'برسوخ', 'الفن', 'المصري', 'القديم', 'وفنون', 'النقش', 'العربي', 'كما', 'يضع', 'الأيدي', 'على', 'مصادر', 'القوة', 'بأي', 'مجتمع']
650
['فكرة', 'البابا', 'من', 'مقر', 'إقامته', 'الصيفي', 'كاستل', 'جاندولفو', 'إنه', 'شعر', 'بالسعادة', 'يوم', 'السبت', 'للقائه', 'ببطريرك', 'الطائفة', 'المسيحية', 'الكلدانية', 'ببغداد', 'والذي', 'يسعى', 'من', 'أجل', 'الإفراج', 'عن', 'قسيس', 'تم', 'اختطافه', 'في', 'بغداد']
700
['من', 'إنه', 'لمن', 'دواعي', 'السرور', 'أن', 'تغتنم', 'دولة', 'قطر', 'أميراً', 'وحكومة', 'وشعباً', 'العودة', 'الميمونة', 'لحضرة', 'صاحب', 'السمو', 'الشيخ', 'جابر', 'الأحمد', 'الصباح', 'أمير', 'دولة', 'الكويت', 'إلي', 'بلده', 'العزيز', 'معافي', 'بحول', 'الله', 'ورعايته', 'لتتقدم', 'إلي', 'سموه', 'الكريم', 'وإلي', 'الشعب', 'الكويتي', 'الشقيق', 'وحكومة', 'دولة', 'الكويت', 'بأسمي', 'عبارات', 'التهاني', 'الأخوية', 'الصادقة', 'داعين', 'لسموه', 'بموفور', 'الصحة', 'والعافية', 'و', 'تمام', 'الهناء', 'بين', 'أهله', 'وشعبه', 'ليواصل', 'خدمة', 'بلده', 'وأمته']
750
['لدى', 'عطا', 'أكثر', 'صمتاً', 'عن', 'الجراح', 'اللبناني', 'المولد', 'الذي', 'كان', 'يضحك', 'ويبتسم', 'طوال', 'التسجيل', 'فيما', 'كان', 'الأول', 'يومي', 'برأسه', 'قبيل', 'أن', 'يأخذ', 'النقاش', 'بينهما', 'طابعاً', 'جدياً']
800
['أبو', 'بارع', 'يعرف', 'أكثر', 'لأعماله', 'السريالية', 'المميّزة', 'بصورها', 'الغريبة', 'الشبيهة', 'بالأحلام']
850
['جلسة', 'الدقائق', 'المتبقية', 'لم', 'تتغير', 'النتيجة', 'بالرغم', 'من', 'كافة', 'محاولات', 'الشباب', 'المتواصلة', 'التي', 'منعها', 'دفاع', 'الحسين', 'وابعد', 'خطورتها', 'حتى', 'وصلت', 'الامور', 'الى', 'حد', 'التوتر', 'ونال', 'على', 'اثر', 'ذلك', 'احمد', 'ابو', 'عرقوب', 'لاعب', 'الشباب', 'البطاقة', 'الحمراء', 'لالتحامه', 'مع', 'عثمان', 'عبيدات', 'قبل', 'ان', 'تنتهي', 'المباراة', 'بدقيقة']
900
['الألمان', 'واشنطن', 'أن', 'سولانا', 'فشل', 'حتى', 'الآن', 'في', 'تحقيق', 'تقدم', 'قبل', 'نهاية', 'المهلة', 'التي', 'منحت', 'له', 'لإقناع', 'الإيرانيين', 'بوقف', 'التخصيب']

In [ ]:
print(len(predicted_data[0][1] ),'\n', len(data_values[0][1]) ,'\n', len(data_values[0][0]))

40
 40
 40

In [ ]:
grouped_data = []
count = 0
for words, true_label in data_values:
    pred_words, pred_label = predicted_data[count]
    count +=1
    for i, word in enumerate(words):
      if word == pred_words[i] :
        grouped_data.append([word, true_label[i], pred_label[i]])
      else:
        grouped_data.append([word, true_label[i], pred_label[i]])

In [ ]:
import pandas as pd



df = pd.DataFrame(grouped_data, columns=['Word', 'Target', 'Predicted'])
df['Target'] = df['Target'].map({
    "B-PERS":"per", "I-PERS"	:"per", "O":"O",
    "B-LOC": "loc",  "B-evnt": "evnt","B-ORG": "org","B-MISC": "misc",
    "I-LOC": "loc",  "I-evnt": "evnt","I-ORG": "org","I-MISC": "misc",
    })

df

           Word Target Predicted
0      الصالحية    loc       loc
1        المفرق    loc       loc
2           غيث    per       per
3      الطراونة    per       per
4           أمر      O         O
...         ...    ...       ...
22504   الوزيرة      O         O
22505       ابن      O         O
22506     وابنة      O         O
22507      خالد    per       per
22508      وريم    per       per

[22509 rows x 3 columns]

In [ ]:
df = df.dropna()

In [ ]:
from sklearn.metrics import classification_report
report = classification_report(list(df['Target']), list(df['Predicted']))
print(report)

              precision    recall  f1-score   support

           O       0.98      0.99      0.99     19138
         loc       0.88      0.94      0.91       751
        misc       0.81      0.50      0.62       398
         org       0.82      0.74      0.78       725
         per       0.93      0.93      0.93      1496

    accuracy                           0.97     22508
   macro avg       0.89      0.82      0.84     22508
weighted avg       0.97      0.97      0.97     22508

In [ ]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(df['Target'], df['Predicted'], labels=['loc', 'misc', 'org', 'per', 'O'])

In [ ]:
conf_matrix

array([[  703,     1,    10,     5,    32],
       [   24,   198,    31,    11,   134],
       [   34,     6,   534,    35,   116],
       [   14,    12,    21,  1384,    65],
       [   20,    28,    53,    49, 18988]])

In [ ]:
digits_convert ={"loc": 1,  "misc": 2,"org": 3, "per": 4, "O": 5,}
df['Target'] = df['Target'].map(digits_convert)
df['Predicted'] = df['Predicted'].map(digits_convert)
df.head()

<ipython-input-131-5d7feae604e2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Target'] = df['Target'].map(digits_convert)
<ipython-input-131-5d7feae604e2>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Predicted'] = df['Predicted'].map(digits_convert)

       Word  Target  Predicted
0  الصالحية       1          1
1    المفرق       1          1
2       غيث       4          4
3  الطراونة       4          4
4       أمر       5          5

In [ ]:
from sklearn.metrics import f1_score
labels_ = {}
f1_score(df['Target'], df['Predicted'], average='macro')

0.8437080707397353

In [ ]:
f1_score(df['Target'], df['Predicted'], average='micro')

0.9688555180380309

In [ ]:
f1_score(df['Target'], df['Predicted'], average='weighted')

0.9673000034849879

In [ ]:
f1_scores =f1_score(df['Target'], df['Predicted'], average=None)

In [ ]:

results = pd.DataFrame(conf_matrix, columns=['loc', 'misc', 'org', 'per', 'O'])
results['f1_score'] = f1_scores
results

   loc  misc  org   per      O  f1_score
0  703     1   10     5     32  0.909444
1   24   198   31    11    134  0.615863
2   34     6  534    35    116  0.777293
3   14    12   21  1384     65  0.928859
4   20    28   53    49  18988  0.987082